### ISSUE TITLE
transformation.py building warn

### ISSUE THREAD

**Issue by ierosodin** [RobotLocomotion/pytorch-dense-correspondence#153]
When building file that imports transformations.py, I get a warning "UserWarning: failed to import module _transformations".
I just comments out "_import_module('_transformations')" in transformation.py now. I am wondering if it's safe to ignore this code.

**Comment by manuelli** [comment]
I believe this warning is safe to ignore. It's essentially the same as [this](https://github.com/mikeroberts3000/flashlight/issues/3) issue,.

**Comment by peteflorence** [comment]
@ierosodin just to follow up on this -- we have got rid of this warning! Since https://github.com/RobotLocomotion/pytorch-dense-correspondence/pull/165/commits/57afc8bd1d3bc8b6cd4c0a6ecc639c20699397e8

**Comment by ierosodin** [comment]
Thanks for your reply.
