### ISSUE TITLE
Would you please provide a pretrained model?

### ISSUE THREAD

**Issue by Wegnery219** [RobotLocomotion/pytorch-dense-correspondence#154]
It's so complex for me to get the data.Would you please provide a pretrained model?I want to see the project effect and try the evaluate function.

**Comment by manuelli** [comment]
Yes we will do this eventually, along with some sample data so you can evaluate the network.

**Comment by Wegnery219** [comment]
Thank you for your reply.

**Comment by peteflorence** [comment]
Hi @Wegnery219, @jiamingsuen --
We have now made all of our data available!
This [tutorial](https://github.com/RobotLocomotion/pytorch-dense-correspondence/blob/master/doc/tutorial_getting_started.md) will walk through downloading the data and training a model.
If you are familiar with this type of software and have a new-ish GPU, I estimate only would take ~30 minutes to get a model trained and results visualized.
Let me know if you get caught up, or we could make anything more clear?

**Comment by vonHartz** [comment]
> Hi @Wegnery219, @JiamingSuen -- We have now made all of our data available! This [tutorial](https://github.com/RobotLocomotion/pytorch-dense-correspondence/blob/master/doc/tutorial_getting_started.md) will walk through downloading the data and training a model. If you are familiar with this type of software and have a new-ish GPU, I estimate only would take ~30 minutes to get a model trained and results visualized. Let me know if you get caught up, or we could make anything more clear?

Thank you for your work and open-sourcing it. Would you mind sharing a pretrained model @manuelli @peteflorence ? I try to re-create your `Self-Supervised Correspondence in Visuomotor Policy Learning` paper, which builds on the pre-trained model.

Nvm. I found the model zoo now.
