### ISSUE TITLE
Change Detection Pipeline can not find directorPython

### ISSUE THREAD

**Issue by iskanderuse** [RobotLocomotion/pytorch-dense-correspondence#177]
Script run_change_detection_pipeline.py throws error: directorPython not found inside pdc-docker.
What is the "directorPython"? And how to find it?

**Comment by iskanderuse** [comment]
I try to I'm trying to apply pdc on my robot installation. Director binaries are available now. May be this issue due to commented #build_director in master branch.. (https://github.com/RobotLocomotion/pytorch-dense-correspondence/issues/171#issuecomment-428281322)

**Comment by manuelli** [comment]
Yes you are exactly right. Now that the director binaries are available you should be able to build director as part of the docker build. @iskanderuse if you know what to comment/uncomment that's worth a try. We will submit a PR with a fix as soon as we can.

**Comment by manuelli** [comment]
Fixed by #179
