### ISSUE TITLE
Can I have the pre-trained models from demo?

### ISSUE THREAD

**Issue by HugeKangroo** [RobotLocomotion/pytorch-dense-correspondence#188]
Hello, could I have the pre-trained models which showed in demos with hats and shoes?

**Comment by manuelli** [comment]
We are working on getting these uploaded, hopefully they will be up by the end of the week. Sorry for the delay.

**Comment by HugeKangroo** [comment]
That will be great and Thank you !

**Comment by manuelli** [comment]
Hi,

Sorry for the delay. The pre-trained models are now uploaded. See our ['model_zoo.md`](https://github.com/RobotLocomotion/pytorch-dense-correspondence/blob/master/doc/model_zoo.md) document. That should have links to the various models used in the demos, and you should be able to evaluate those models on our supplied data.
