### ISSUE TITLE
Getting started tutorial not working

### ISSUE THREAD

**Issue by Ademord** [RobotLocomotion/pytorch-dense-correspondence#192]
Hello

I have followed your [Getting Started Tutorial](https://github.com/RobotLocomotion/pytorch-dense-correspondence/blob/master/doc/tutorial_getting_started.md), and after a whole day of fixing dependencies and build problems, have decided to give up because it's just not feasible to run this.

After building the image, and then running it, the dependencies in the first notebook (test) are all messed up; modules are importing from a parent directory and don't have the "modules.x" prefix, which makes the jupyter notebook blow up, error after error.
I created a notebook on the root of dense-correspondence, and then fixed on my local sandbox, all the dependencies. Finally, the first (test) notebook you point to, works.

Then I go into the training_notebook, and ran into [this issue](https://github.com/warmspringwinds/pytorch-segmentation-detection/issues/11): ```_init__() got an unexpected keyword argument "fully_conv"```, which had me clean up your dependency install file (pytorch outdated, pip outdated; reminder: there's only 7 months left of support for python 2.7..), which I have not been able to fix and has made me come here to ask for help. Do you have any idea about this problem? 

Appendix

Example the dependencies in your notebooks dont work outside of the box (modules.x prefix missing):
![image](https://user-images.githubusercontent.com/4501464/57235791-f51d1180-7023-11e9-8910-7c7e3fcec3f4.png)

Second error I haven't been able to fix:
![image](https://user-images.githubusercontent.com/4501464/57235919-43321500-7024-11e9-9b1c-3aaace483c57.png)

**Comment by manuelli** [comment]
Hi,

It seems like maybe some of the environment variables didn't get properly sourced. Try running

```
use_pytorch_dense_correspondence ## this sets necessary environment variables
```

before launching the notebook and see if that helps. I think this is detailed in our tutorial but if not let us know and we can fix it.

**Comment by manuelli** [comment]
Your second error is related to the fact that we use a custom fork of pytorch/vision which does support the `fully_conv` argument. You are probably loading the standard pytorch/vision since environment variables maybe haven't been set correctly due to the aforementioned issue.

FYI the custom fork we use is here https://github.com/warmspringwinds/vision/tree/5e0a760fc847d55a4c1699410a14003452fa4581

**Comment by peteflorence** [comment]
Hi @Ademord , yes I think you are just missing that part of Step 5 that Lucas pointed out.  That will probably fix all of your problems, but let us know if it doesn't.

**Comment by peteflorence** [comment]
Also feel free to try to change all the versions of all the dependencies, but it should just work if you keep to the ones we provided.  The reason we provide it in a docker format is so that all these dependencies can be well tracked, and the libraries are contained to this project only.

Also we have a version of this working with pytorch 1.0 on a private branch, was a bit of work to get there but we will release it eventually.

**Comment by Ademord** [comment]
Hello,
I tried installing from source from the fork repo you mentioned and it still doesn't work. 
Is there another way to test this module is properly installed? 

The env vars are set but the ```fully_conv``` problem persists...

**Comment by manuelli** [comment]
Hi,

So there is no need to do any additional installation, if you follow the tutorial everything you need is there.. Can you confirm that (as detailed in the tutorial) you have run 

```
git submodule update --init --recursive
```

before building the docker image. My guess is that you missed this command and so you don't have the aforementioned fork of torchvision in your source tree. In your jupyter notebook please check where your `torchvision` is. It should be in the source tree, as in the code snippet below. 

```
>>>import dense_correspondence.network.dense_correspondence_network
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
>>> import torchvision
>>> torchvision.__file__
'/home/manuelli/code/pytorch-segmentation-detection/vision/torchvision/__init__.pyc'
```

You shouldn't be impoting the system installed version, which is what would happen if you didn't do the `git submodule update --init --recursive` call). 



```
>>> torchvision.__file__
'/usr/local/lib/python2.7/dist-packages/torchvision/__init__.pyc'
```
In general it seems like maybe you missed one or two steps in the turotial/setup so it may be worth going through that again from scratch and just make sure you have done everything correctly.

**Comment by Ademord** [comment]
Hi,
I removed all my files 😂 and cloned again, followed the steps carefully. I am on the first notebook, and torchvision is on the proper path as you showed 👍🏻

Now, I get the following error: ```AttributeError: 'module' object has no attribute 'float32'```.

It seems like this is because of a newer torchtext version thats not compatible with our older torch version... I tried with ``` pip install torchtext==0.2.3``` and it's still not working 😕

**Comment by Ademord** [comment]
Okay, I think I got it. GEEZ.

1. I removed the (freakin') torchvision from your install_pytorch.sh
2. I assume your use_pytorch_ setup doesnt work because torchvision was not being found.
3. I looked at what the guys at pytorch-segmentation did, and they have this code in their notebooks:
``` 
import sys
sys.path.insert(0, '/home/ribr/code/pytorch-segmentation-detection/vision/')
```
4. Now **all** the first notebook runs. I am going to go to the other ones.

**Comment by peteflorence** [comment]
Glad you also figured it out.

This is addressed in our code by the following line: https://github.com/RobotLocomotion/pytorch-dense-correspondence/blob/c6cb473a7ee44ac4eb1015365b4f20e69f19336a/modules/dense_correspondence_manipulation/utils/utils.py#L115

This is why `add_dense_correspondence_to_python_path()` is at the start of every notebook.

**Comment by Ademord** [comment]
Thanks! Interestingly it didn't run on mine (new, clean download).

I think it would be good to have an assert in case it doesnt import it in the beginning for a user ? (verify that torchvision.__file__ is at X location ?

Now, on the training tutorial notebook i get this error:
```ValueError: scene_name = 2018-04-10-16-02-59 doesn't exist```

**Comment by Ademord** [comment]
Update: so I figured out that problem 2 assumes there is some hardcoded 3500 somewhere else for the number of iterations (which in the notebook is variable). 
I trained for the 3500 iterations and it's all good.

In these images, are we seeing the cross-object loss? and could you please help me understand a bit more of this concept? 
![image](https://user-images.githubusercontent.com/4501464/57388492-976dfe00-71b8-11e9-97d1-5b910228dce1.png)


And also, how can I better understand the descriptor images? 
![image](https://user-images.githubusercontent.com/4501464/57388556-bc627100-71b8-11e9-96e9-62835284a05c.png)

I'm going to re-read your paper in the meantime.
