### ISSUE TITLE
invalid tensor shape

### ISSUE THREAD

**Issue by Ademord** [RobotLocomotion/pytorch-dense-correspondence#193]
Hello!
How could the correct shape (the additional [1,1]) be fixed?

<img width="890" alt="image" src="https://user-images.githubusercontent.com/4501464/57612651-838a1980-7575-11e9-8040-12e961fdbfe6.png">

**Comment by priyasundaresan** [comment]
Having the same issue,^ did you manage to resolve it?

**Comment by priyasundaresan** [comment]
Resolved. In train.py, make sure that line 153 is changed to:
self.fc = nn.Linear(512 * block.expansion, num_classes) instead of:
self.fc = nn.Conv2d(512 * block.expansion, num_classes, (1, 1))

If you do:
print(self.fc.weight.size()), you'll see the torch.Size is now (1000, 512)

**Comment by kingsman142** [comment]
@priyasundaresan I was just having this problem. Your solution worked perfectly!

**Comment by manuelli** [comment]
Thanks for the solution @priyasundaresan. I will look into this and PR a fix.

**Comment by manuelli** [comment]
I have just tested the full tutorial against the branch in PR #196 and everything seems to be working fine. Note that the new PR requires `nvidia-docker2` instead of just `nvidia-docker` so you may need to re-install that if you are on an older version of `nvidia-docker`.

**Comment by priyasundaresan** [comment]
Thanks for your quick response and help @manuelli!
