### ISSUE TITLE
Training tutorial quantitative eval

### ISSUE THREAD

**Issue by priyasundaresan** [RobotLocomotion/pytorch-dense-correspondence#195]
Hi there, any idea what would be causing this error in the last cell of [training_tutorial.ipynb](https://github.com/RobotLocomotion/pytorch-dense-correspondence/blob/master/dense_correspondence/training/training_tutorial.ipynb)?

Can't seem to track down where the indexing issue is and didn't see any similar issues posted:

![Screenshot from 2019-05-27 13-05-46](https://user-images.githubusercontent.com/36607229/58437957-26b45600-8081-11e9-8cfa-f5e03b56b72b.png)

Thank you very much in advance for the help!!

**Comment by manuelli** [comment]
I actually just fixed this issue in a private branch that updates the entire repo to pytorch 1.1 (PR coming soon). In the mean time this is just like a 2 line fix. See the screenshot below (sorry to do a screenshot but it's in another repo and this is the easiest way to link it).

![image](https://user-images.githubusercontent.com/5898488/58438413-c0d5c780-809c-11e9-9b60-613928a40556.png)
