### ISSUE TITLE
REGARDING CLASS CONSISTENT DESCRIPTORS

### ISSUE THREAD

**Issue by ghost** [RobotLocomotion/pytorch-dense-correspondence#202]
Heyy, Firstly great work.
As there wasnt much info about class consistent descriptors in the paper,I would like to how it's done the training procedure requried for that,ike how correspondences are labelled for training and all.
Thankyou in advance.

**Comment by peteflorence** [comment]
Hi there, Section 5.3 describes the class consistent descriptors. The
labeling is only provided automatically by multi-view geometry from static
scenes of a single object at a time. The training procedure is exactly the
same as training descriptors for a single object, except the dataset
includes multiple instances from the class.
