### ISSUE TITLE
Downloading data set Issue

### ISSUE THREAD

**Issue by natkalin** [RobotLocomotion/pytorch-dense-correspondence#205]
Attempted to download data set from https://data.csail.mit.edu/labelfusion/pdccompressed/ and get 403 forbidden error. Cannot run download_pdc_data.py without downloading data. Am I missing something?

**Comment by peteflorence** [comment]
Hi there, did you try running the script from the tutorial? https://github.com/RobotLocomotion/pytorch-dense-correspondence/blob/master/doc/tutorial_getting_started.md

For reference, if I run this below I get a 403 error:

```
wget https://data.csail.mit.edu/labelfusion/pdccompressed/
```

But with this command it downloads ok:
```
wget https://data.csail.mit.edu/labelfusion/pdccompressed/evaluation_labeled_data_compressed.tar.gz
```
The script should manage the downloading okay (it basically just builds up a bunch of wget commands). Let us know if it's not working for you. There could be an issue with the server, but I did just test downloading the file above and it seemed okay.
