### ISSUE TITLE
Find corresponding pixel in the image of vertices in fusion_mesh.ply

### ISSUE THREAD

**Issue by lix4** [RobotLocomotion/pytorch-dense-correspondence#214]
Hello, maybe this is irrelevant with this project. I am trying to find x and y coordinate the image of a vertex in mesh. I just use K*transform_matrix*(X,Y,Z,1) (vertex coordinate in mesh.). But I got incorrect pixels. Is there anything wrong with doing this? Thank you!

**Comment by manuelli** [comment]
Projecting a world point into camera frame is just done using the pinhole camera model, see [OpenCV documentation](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html). This is a simple transformation to write and the purpose of this repo is not to be a library for projective geometry.
