### ISSUE TITLE
camera synchronization

### ISSUE THREAD

**Issue by guri-dominic** [RobotLocomotion/pytorch-dense-correspondence#215]
Can you share the details about the camera synchronization? A few blogs about synchronization via connecting cameras, but your video does not show a direct camera-camera connection.

**Comment by manuelli** [comment]
The cameras were synchronized using the image timestamps given by the camera driver. This was sufficient for our purposes. I believe the Intel realsense cameras also support using a hardwired connection between the physical cameras to perform synchronization.
